#pragma kernel CSMain

struct Light 
{
    float3 pos;
    float3 color;
    float intensity;
};


float step;

float3 cameraPosition;
float4x4 cameraMatrix;
uint2 resolution;

float boxSize;
int boxResolution;

float schlick_k;
float scatter;

RWTexture3D<float> noise;
RWTexture2D<float4> result;
StructuredBuffer<Light> lights;

#define MAX_DIST    100.0
#define MAX_STEPS   1000
#define DIM_CUTOFF  0.01

#define PI          3.14159265359
#define EPS         0.001  

float lengthSqr(float3 delta)
{
    return dot(delta, delta);
}

float hash(inout uint seed) {
  uint num = seed++;
  num = num * 747796405u + 2891336453u;
  num = ((num >> ((num >> 28u) + 4u)) ^ num) * 277803737u;
  num = (num >> 22u) ^ num;
  return float(num) * (1.0 / 4294967296.0);
}

uint GetPixelSeed(uint2 id)
{
    return uint(id.y * 65171993u + id.x * 11591131u);
}

float GetSchlick(float ang_cos) 
{
    return (1.0 - schlick_k * schlick_k) / 
    (4.0 * PI * (1.0 - schlick_k * ang_cos) * (1.0 - schlick_k * ang_cos));
}

int3 GetCellPosInt(float3 worldPos)
{
    return int3(trunc(worldPos / boxSize * boxResolution));
}

float3 GetCellPosFloat(float3 worldPos)
{
    return worldPos / boxSize * boxResolution;
}

float SampleNoise(float3 worldPos)
{
    float3 cPosFloat = GetCellPosFloat(worldPos);
    float3 cPosDelta = cPosFloat - trunc(cPosFloat);

    int3 cPosInt = GetCellPosInt(worldPos);
    cPosInt.x += (cPosDelta.x <= 0.5) ? -1 : 0;
    cPosInt.y += (cPosDelta.y <= 0.5) ? -1 : 0;
    cPosInt.z += (cPosDelta.z <= 0.5) ? -1 : 0;

    int3 cPosA = int3(cPosInt.x,     cPosInt.y,  cPosInt.z);
    int3 cPosB = int3(cPosInt.x + 1, cPosInt.y,  cPosInt.z);
    int3 cPosC = int3(cPosInt.x,     cPosInt.y,  cPosInt.z + 1);
    int3 cPosD = int3(cPosInt.x + 1, cPosInt.y,  cPosInt.z + 1);

    int3 cPosE = int3(cPosInt.x,     cPosInt.y + 1,  cPosInt.z);
    int3 cPosF = int3(cPosInt.x + 1, cPosInt.y + 1,  cPosInt.z);
    int3 cPosG = int3(cPosInt.x,     cPosInt.y + 1,  cPosInt.z + 1);
    int3 cPosH = int3(cPosInt.x + 1, cPosInt.y + 1,  cPosInt.z + 1);

    cPosA = min(max(cPosA, 0), boxResolution - 1);
    cPosB = min(max(cPosB, 0), boxResolution - 1);
    cPosC = min(max(cPosC, 0), boxResolution - 1);
    cPosD = min(max(cPosD, 0), boxResolution - 1);

    cPosE = min(max(cPosE, 0), boxResolution - 1);
    cPosF = min(max(cPosF, 0), boxResolution - 1);
    cPosG = min(max(cPosG, 0), boxResolution - 1);
    cPosH = min(max(cPosH, 0), boxResolution - 1);

    float valA = noise[cPosA];
    float valB = noise[cPosB];
    float valC = noise[cPosC];
    float valD = noise[cPosD];

    float valE = noise[cPosE];
    float valF = noise[cPosF];
    float valG = noise[cPosG];
    float valH = noise[cPosH];

    float3 d = cPosFloat - float3(cPosA) - 0.5; 
    d = max(d, 0.0);
    float bot = lerp(lerp(valA, valB, d.x), lerp(valC, valD, d.x), d.z);
    float up =  lerp(lerp(valE, valF, d.x), lerp(valG, valH, d.x), d.z);
    float final = lerp(bot, up, d.y);
    return final;
}

float3 TraceLight(float3 pos, float3 mainDir, inout uint seed)
{
    uint lightsCount, _;
    lights.GetDimensions(lightsCount, _);
    

    float3 accum = 0.0;
    for (int i = 0; i < lightsCount; i++)
    {
        float3 tempPos = pos;

        Light light = lights[i];
        float3 dir = normalize(light.pos - tempPos);

        float transparency = 1.0;
        for (int j = 0; j < MAX_STEPS; j++)
        {
            if (transparency < DIM_CUTOFF)
                break;

            int3 cpos = GetCellPosInt(tempPos);
            if (any(cpos < 0) || any(cpos >= boxResolution))
                break;

            if (lengthSqr(light.pos - tempPos) < step * step)
                break;

            float3 randOffset = hash(seed) * step * dir;
            transparency *= exp(-step * SampleNoise(tempPos + randOffset) * scatter);
            tempPos += dir * step;
        }

        float distFactor = 2.0 / (lengthSqr(light.pos - tempPos) + 1.0);
        float3 schlickFactor = GetSchlick(dot(mainDir, dir));
        
        accum += transparency * light.intensity * distFactor * schlickFactor * light.color;
    }

    return accum;
}



[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (any(id.xy >= resolution))
        return;

    uint seed = GetPixelSeed(id.xy);
    
    float3 pos = cameraPosition;
    float3 dir = mul(cameraMatrix, float4(id.xy + float2(0.5, 0.5), 1.0, 1.0));
    float dist = 0.0;

    float transparency = 1.0;
    float3 accum = 0.0;

    for (int i = 0; i < MAX_STEPS; i++)
    {
        if (dist > MAX_DIST)
            break;

        if (transparency < DIM_CUTOFF)
            break;

        pos += dir * step;
        dist += step;

        int3 cpos = GetCellPosInt(pos);
        if (any(cpos < 0) || any(cpos >= boxResolution))
            continue;

        float noiseVal = noise[cpos];
        if (noise[cpos] < EPS)
            continue;

        float3 randOffset = hash(seed) * step * dir;
        float3 light = step * TraceLight(pos + randOffset, dir, seed);
        accum += transparency * light;
        transparency *= exp(-step * SampleNoise(pos));
    }

    result[id.xy] = float4(accum, 1.0);
}
